---
title: "Exploratory Data Analysis"
subtitle: "可重复性报告 - 作为报告草稿"
documentclass: ctexart
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: yes

    keep_md: yes
    keep_tex: yes
    includes:
      in_header: "preamble.tex"
geometry: left=2cm, right=2cm, top=2.5cm, bottom=2.5cm
monofont: Fira Mono
---

# 环境

## R info
```{r include = FALSE}
library(readr)
library(tidyr)
library(dplyr)

library(stringr)
library(purrr)

library(lubridate)
```

```{r comment = ""}
xfun::session_info(packages = c("readr", "tidyr", "stringr", "dplyr", "purrr", "lubridate"),
                   dependencies = FALSE)
```

## python info

// TODO

# 分析

## The Workflow

![The Data Science Workflow[^1]](workflow.png)

[^1]: This picture is from [R for Data Science](https://r4ds.had.co.nz/introduction.html) by Hadley Wickham and Garrett Grolemund, released under [CC BY-NC-ND 3.0 US](http://creativecommons.org/licenses/by-nc-nd/3.0/us/).

## Import

// 需要数据集的完整描述和获取方式

// TODO - **R. Li**

## Tidy

```{r cache = TRUE, message = FALSE}
raw_df <- read_csv("./data/investment/FDI_untidy.csv")

process <- function(raw_df) {
  simplified_df <- raw_df %>%
    filter(X1 %>% str_detect("^\\d")) %>%
    rename(时间 = X1)

  fliped_df <- simplified_df %>%
    pivot_longer(c(-时间), names_to = "observation", values_to = "val")

  stdize <- function(str) {
    str %>%
      str_replace(pattern = "(.*):(总计|一带一路)", replacement = "\\1/\\2/\\2") %>%
      str_replace(pattern = "::", replacement = ":") %>%
      str_replace(pattern = "(.*):(.*洲):*(.*)", replacement = "\\1/\\2/\\3")
  }

  sep_df <- fliped_df %>%
    mutate(observation = observation %>% stdize()) %>%
    separate(col = "observation", into = c("type", "地区", "国家"), sep = "/")

  df <- sep_df %>% spread(key = "type", value = "val")
}

raw_df %>%
  process() %>%
  write_csv("./data/investment/FDI_tidy.csv")

cont <- raw_df %>%
  filter(X1 == "状态") %>%
  as_vector() %>%
  .[. == "继续"] %>%
  names()
raw_df %>%
  select(X1, all_of(cont)) %>%
  process() %>%
  write_csv("./data/investment/FDI_tidy_cont.csv")
```

```{r cache = TRUE}
raw_df <- read_csv(
  file = "./data/investment/FDI_tidy_cont.csv",
  col_types = cols(
    时间 = col_date(format = "%m/%Y")
  ),
  guess_max = 50000
)

df0 <- raw_df %>%
  filter(!is.na(国家))

# 对外直接投资:非金融类:累计 为一带一路数据所特有
OBOR_col <- "对外直接投资:非金融类:累计"

df <- df0 %>%
  filter(国家 != "一带一路" & 国家 != "总计") %>%
  select(-all_of(OBOR_col))

df <- df %>%
  filter(month(时间) == 12) %>%
  mutate(年份 = as.integer(year(时间)), .keep = "unused", .before = 1) %>%
  filter(年份 >= 2002)

df <- df %>%
  select(names(df) %>% str_subset(pattern = "投资(和其他)*$", negate = TRUE)) %>%
  filter(!is.na(`对外直接投资:截至累计`))

df %>% write_csv(file = "./data/investment/FDI_useful.csv")

df1 <- df0 %>%
  filter(国家 == "一带一路" & !is.na(.[OBOR_col])) %>%
  select(时间, all_of(OBOR_col)) %>%
  mutate(
    年份 = as.integer(year(时间)),
    月份 = as.integer(month(时间)),
    .keep = "unused", .before = 1) %>%
  arrange(年份, 月份)

df1 %>% write_csv(file = "./data/investment/FDI_OBOR.csv")
```

## Understand

// TODO... - R. Deng

## Communicate

// Use **echarts**, maybe [**pyecharts**](https://github.com/pyecharts)?

// TODO - H. Fan

# 总结


